---
# tasks file for aerospike-Centos
- name: updating all packages.
  yum: name=* state=latest
- name: Create Aerospike download directory
  file:
    path: "{{ aerospike_source_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

# creating aerospikes log directory
- name: Create Aerospike log directory.
  file:
    path: "{{ aerospike_log_directory }}"
    state: directory

# downloading the package
- name: Downloading Aerospike package.
  unarchive:
    src: https://www.aerospike.com/download/server/{ aerospike_version }}/artifact/{{Centos_version}}
    dest: "{{aerospike_source_directory}}"
    remote_src: true
    list_files: yes
    validate_certs: no
  register: archive_contents

# updating package name

- name: Getting Names of Aerospike rpm Packages.
  find:
    path: "{{aerospike_source_directory}}/{{ archive_contents.files[0].split('/')[0] }}"
    patterns: "^(aerospike-(?:server|tools).+\\.rpm)$"
    use_regex: true
  register: aerospike_rpm

# Installing the aerospikes dependencies
- name: installing rpm dependices
  yum:
    name: ['python36']
    state: present
    update_cache: yes

# Installing the aerospike
- name: Installing Aerospike package from rpm.
  yum:
    name: "{{ item.path }}"
    state: present
  with_items:
    - "{{ aerospike_rpm.files }}"

# it will place the config file in the default directory

- name: Place Aerospike configuration file.
  template:
    src: aerospike.conf.j2
    dest: "{{ aerospike_config_destination }}"
    owner: root
    group: root
    force: yes
  notify:
    - start_aerospikes
    - Make Sure Cluster Memembership Is Correct

# installing aerospikes Management Console
- name: Installing Aerospikes webconsole
  get_url:
    url: "http://www.aerospike.com/download/amc/{{ amc_version }}/artifact/el6"
    dest: "{{aerospike_source_directory}}"
  register: amc_file

# updating and setting up the amc
- name: Updating the repo with amc
  yum:
    name: “{{ item }}”
    state: latest
    update_cache: yes
  with_items:
    - "{{ amc_file.files }}"
    - gcc
    - python-devel
  notify:
    - start_amc



