---
# tasks file for aerospikes
- debug:
    msg: "{{ ansible_os_family }}"
- include_tasks: debian.yml
  when:  ansible_os_family == 'Debian'
- include_tasks: centos.yaml
  when:  ansible_os_family == 'RedHat'